/var/log/suricata/eve.json {
    size 50M
    rotate 2
    compress
    missingok
    notifempty
    copytruncate
}

/var/log/suricata/stats.log /var/log/suricata/fast.log {
    size 10M
    rotate 2
    compress
    missingok
    notifempty
    copytruncate
}
